### ISSUE TITLE
Modifying navbar during routing request

### ISSUE THREAD

**Issue by ser** [mbr/flask-nav#1]
Hi,
navbar definition in the flask-nav example is above any routing element.

Is it possible to add some navigational elements inside for example:

```
@app.route('/about-us/')
   <here i want to add some navbar elements>
```

and if yes, how?

**Comment by mbr** [comment]
With the code example, I am not a 100% what you are trying to accomplish, but have you checked out http://pythonhosted.org/flask-nav/advanced-topics.html#dynamic-construction ?

For what I think you're trying to do, you have two choices: Either generate the navbar dynamically and add extra information based on the endpoint:

``` python
@nav.navigation
def top_nav():
    n = Navbar(...)
    if request.endpoint == 'frontend.about_us':
        n.items.append(....)   # add whatever extra you need here
    return n
```

or create a copy inside the view, modify it and pass that to the template as a variable.

**Comment by ser** [comment]
> create a copy inside the view, modify it and pass that to the template as a variable

Hi, thanks, it is a perfect solution for me, it's shame that I did not find it out by myself :)

Thanks a lot, Marc!

**Comment by slippers** [comment]
New to python stuff:)  
I'm having issues with customizing the Navbar.  After working through this I think I need to compose a tuple of nav elements and then create the Navbar with that list.

Navbar.items is a tuple?  so it cannot be appended to. Constructor only  to fix I did this.  Is there a better way?  converting to a from a tuple is tedious.  How can I change that.

```
@nav.navigation()
def mainnav():
    # ... 
    return Navbar('main', ...)

@nav.navigation()
def xraynav():
    xray = list(mainnav().items)
    xray.append(View('cat', catroute'))
    return Navbar('xraynav', *(tuple(xray)))

```

**Comment by mbr** [comment]
You do not need to convert to a tuple to pass *args:

``` python
@nav.navigation()
def xraynav():
    xray = list(mainnav().items)
    xray.append(View('cat', catroute'))
    return Navbar('xraynav', *xray)
```

The example above can be written fairly concise using tuple-concatenation:

``` python
@nav.navigation()
def xraynav():
    return Navbar(*mainnav().items + (View('cat', catroute),))
```

Although restructuring how you generate the bars might yield even better results.

**Comment by slippers** [comment]
thanks, \* unpacks the args.
