### ISSUE TITLE
Hide 'Login' button when user authorized

### ISSUE THREAD

**Issue by ape364** [mbr/flask-nav#18]
Hello.

Is there a possibility of interaction with `current_user.is_authenticated` function when building a navigation menu? I want to hide menu item **Login** when user is authorized and to show when not.

Thanks.

**Comment by wgwz** [comment]
i did it in my base.html template with: 

```
{% block navbar %}
{% if current_user.is_authenticated %}
{{ nav.admin.render() }}
{% else %}
{{ nav.top.render() }}
{% endif %}
{% endblock %}
```

where `nav.admin` is what the user should see when logged in. but i would like to see an example from the project author on other ways to do this.

**Comment by slippers** [comment]
mynavbar is public and secnavbar has authentication stuff. secnavbar inherits mynavbar.  can use either in your templates.  configure_nav is called from the space where you create app.

some template
```
{% block navbar %}
{{nav.secnavbar.render()}}
{% endblock %}
```

site_nav.py
```
from flask_login import current_user
from flask_nav import Nav
from flask_nav.elements import Navbar, View, Subgroup
from flask import current_app
from .simple_page import simple_page

def mynavbar():
    return Navbar(current_app.config.get('SITE_NAME'),
                  View('Home', 'simple_page.home'),
                  View('Blog', 'blogging.index'),
                  View('About', 'flat_pages.page', name='about'),
                  Subgroup(
                      'Apps',
                      View('Product A','flat_pages.page', name='producta'),
                      View('Product B','flat_pages.page', name='productb'),
                  ),  
                 )   

def secnavbar():
    secnav = list(mynavbar().items)

    if current_user.is_authenticated:
        secnav.extend([
                View('Blog Editor', 'blogging.editor'),
                View('Profile', 'simple_page.profile'),
                ])  

      if current_user.has_role('admin'):
            secnav.append(
                    View('Admin','admin.index')
                    )

        secnav.append(View('Log out', 'security.logout'))
    else:
        secnav.append(
                View('Log in', 'security.login')
                )

    return Navbar(current_app.config.get('SITE_NAME'), *secnav)


def configure_nav(app):
    nav = Nav()
    nav.register_element('mynavbar', mynavbar)
    nav.register_element('secnavbar', secnavbar)
    nav.init_app(app)
```

**Comment by wgwz** [comment]
@mbr how do you do this sort of thing?

**Comment by slippers** [comment]
to use?  put preceding code into a file called _site_nav.py_

then in your main script file that does stuff like app = Flask()  declare the site_nav and import the configure_nav definition
```
from .site_nav import configure_nav
```
now call configure_nav
```
configure_nav(app)
```

**Comment by wgwz** [comment]
@slippers i understand and like what you do, thanks for sharing! i am just curious to see other ways

**Comment by slippers** [comment]
generally i have to search out all the examples.  then apply my personal
bias and what i like to see.  mainly i like stuff like this to live in its
own file.  and control how it gets configured.  typically example show
inline with other unrelated pieces and break down when the app gets larger.
 also writing these files where you don't import objects like app or db.

**Comment by Jaysins** [comment]
@slippers what's .simple_page?
