### ISSUE TITLE
Please provide doc example of dynamic navbar creation

### ISSUE THREAD

**Issue by mjmare** [mbr/flask-nav#4]
For example: changing the navbar when a user logs in. It would be useful it it showed how to pass information (eg username) to the callable that can be passed to the nav.register_element method.

**Comment by mbr** [comment]
I don't have a lot of time to update the docs right now, but here's a minimal example:

``` python
# app.py

from flask import Flask, render_template
from flask_nav import Nav
from flask_nav.elements import Navbar, View

nav = Nav()

app = Flask(__name__)
nav.init_app(app)


def user_is_logged_in():
    return True


@nav.navigation()
def top_nav():
    items = [View('Home', 'index'), View('Shopping Area', 'index')]

    # only logged in users get to see the secret shop
    if user_is_logged_in():
        items.append(View('Secret Shop', 'secret'))

    return Navbar('', *items)


@app.route('/')
def index():
    return render_template('index.html')


@app.route('/_secret/')
def secret():
    return 'You found the secret shop!'


if __name__ == '__main__':
    app.run(debug=True)
```

``` html
<!-- templates/index.html -->

<html>
<body>
{{nav.top_nav.render()}}
</body>
</html>
```

**Comment by mjmare** [comment]
Very helpful! Thanks

**Comment by strycker** [comment]
user_is_logged_in() cannot read directly from a flask session variable, as it is not inherited.  Do you know of a way to do this?

See this question on StackOverflow:
https://stackoverflow.com/questions/45948609/accessing-flask-session-variables-from-flask-navigation-for-dynamic-navigation-m
