### ISSUE TITLE
How do I adjust the navbar height?

### ISSUE THREAD

**Issue by NathanWailes** [mbr/flask-nav#6]
Hi,

I'm learning Flask and using flask-bootstrap, and I don't like how much vertical space the default bootstrap navbar takes up, and I'm having trouble figuring out how to change that. The [flask bootstrap documentation](https://pythonhosted.org/Flask-Bootstrap/nav.html) has a section called "Customizing the navbar" that says that I'd want to adjust something in flask-nav, but I read the flask-nav documentation and couldn't see a way to adjust the navbar height.

**Comment by mbr** [comment]
Customizing the navbar means changing the markup, but to change its height you'll want to adjust the CSS. All you need is a sufficiently precise CSS selector, if it is your only navbar, you can get away with quite a generic one like `.nav`.

Alternatively you can supply an `id` parameter to the renderer, as in `{{mynav.render(id="mainnav")}}.` This will add an `id="mainnav"` attribute to the resulting HTML.

**Comment by NathanWailes** [comment]
I got it working, thank you for the tip!
